---

- name: Update repositories cache and install Requirements packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - unzip
    - screen

- name: Download Terraria Server
  get_url:  
    url: "{{ download_server_link }}" 
    dest: "/tmp/terraria-server.zip"
    mode: 0644
    validate_certs: false

- name: Create terraria user
  user:
    name: terraria
    password: NOT_LOGGING_PASSWORD
    home: /opt/terraria
    shell: /usr/sbin/nologin
    state: present
    createhome: no
      
- name: Creates work directory
  file:
    path: /opt/terraria
    owner: terraria
    group: terraria
    state: directory

- name: Extract terraria.zip into /opt/terraria
  unarchive:
    src: "/tmp/terraria-server.zip"
    dest: "/opt/terraria"
    mode: 0755
    owner: terraria
    group: terraria
    remote_src: yes

- name: Configure Systemd Service
  copy: 
    src: files/terraria.service 
    dest: /etc/systemd/system/terraria.service
    owner: root
    group: root
    mode: 0664

- name: Configure Terraria script management
  copy:
    src: files/terrariad
    dest: /usr/local/bin/terrariad
    owner: root
    group: root
    mode: 0755

- name: Remove production symlink
  file:
   path: "/opt/terraria/current"
   state: absent

- name: Create production symlink
  file:
    src: "/opt/terraria/{{ version }}"
    dest: "/opt/terraria/current"
    state: link

- name: Set Permission Server Binary
  file:
    path: /opt/terraria/current/Linux/TerrariaServer.bin.x86_64
    owner: terraria
    group: terraria
    mode: '0755'

- name: Creation Configuration File
  template:
    src: "serverconfig.txt.j2"
    dest: "/opt/terraria/current/Linux/serverconfig.txt"
    owner: terraria
    group: terraria
    mode: 0664

- name: Start Terraria Server
  systemd:
    state: started
    name: terraria
    daemon_reload: yes
    enabled: yes